# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Snehal_iOS_Test' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'AFNetworking', '~> 2.5'

  # Pods for Snehal_iOS_Test

  target 'Snehal_iOS_TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Snehal_iOS_TestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
